### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by yurii-hasiuk** [VasyaYovbak/UkraineGroceryPriceAnalytics#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://ukrainegrocerypriceanalytics-89mdzudrkaelcydro66ks2.streamlit.app/vasyayovbak/ukrainegrocerypriceanalytics/main/business_questions.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by VasyaYovbak** [comment]
fixed memory leaks
